services:
  app:
    build: .
    container_name: rss
    image: ghcr.io/limhenry/rss-translate:latest
    ports:
      - '3000:3000'
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
  redis:
    container_name: rss-redis
    image: 'redis:alpine'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
